### ISSUE TITLE
Generate PDF (Ticket) broken

### ISSUE THREAD

**Issue by tobru** [openSUSE/osem#1704]
The link "Generate PDF" generates an internal server error:

```
Started GET "/conferences/dodzh18/physical_ticket/46f1c24b4d4a5c67f2f3.pdf" for 77.56.221.232 at 2017-09-17 12:23:08 +0000
Processing by PhysicalTicketController#show as PDF
  Parameters: {"conference_id"=>"dodzh18", "id"=>"46f1c24b4d4a5c67f2f3"}
Completed 500 Internal Server Error in 196ms (ActiveRecord: 4.7ms)

Prawn::Errors::UnsupportedImageType (PNG uses unsupported interlace method):
  app/pdfs/ticket_pdf.rb:44:in `draw_second_square'
  app/pdfs/ticket_pdf.rb:15:in `initialize'
  app/controllers/physical_ticket_controller.rb:20:in `new'
  app/controllers/physical_ticket_controller.rb:20:in `block (2 levels) in show'
  app/controllers/physical_ticket_controller.rb:17:in `show'
```

**Comment by tobru** [comment]
I could solve this by replacing the conference logo with a JPG image. So I guess this issue can be closed, unless the OSEM team wants to add some error-handling for this case.

**Comment by differentreality** [comment]
Seems that prawn doesn't like some png files. 
We could add an error check in physical_tickets#show and/or https://github.com/openSUSE/osem/issues/1746
