### ISSUE TITLE
Rails console is broken

### ISSUE THREAD

**Issue by olea** [openSUSE/osem#1840]
- [x ] bug

using: 

- docker enviroment
- version: #da735fe1c9b9e685cb9b87987f3048cfebbe7a3e, with no code modifications

First say I'm not a rubyist so maybe I'm obviating something.

I'm said I can access the rails console getting into the docker container and running  «rails console». But console can't start and reports:

```
[olea@lisergia osem]$ docker exec -it osem_web_1 bash 
osem@6e4dd84f4792:/osem$ rails console
NOTE: Gem.datadir is deprecated; use spec.datadir instead. It will be removed on or after 2016-10-01.
Gem.datadir called from /usr/local/bundle/gems/rdoc-generator-fivefish-0.3.0/lib/rdoc/generator/fivefish.rb:29.
/usr/local/bundle/gems/railties-4.2.9/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `web_console' for #<Rails::Application::Configuration:0x0000000005620f48> (NoMethodError)
	from /osem/config/environments/development.rb:5:in `block in <top (required)>'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/railtie.rb:210:in `instance_eval'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/railtie.rb:210:in `configure'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/railtie.rb:182:in `configure'
	from /osem/config/environments/development.rb:1:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/engine.rb:597:in `each'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/engine.rb:597:in `block in <class:Engine>'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `run'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:44:in `each'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:415:in `call'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/application.rb:352:in `initialize!'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/railtie.rb:194:in `public_send'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/railtie.rb:194:in `method_missing'
	from /osem/config/environment.rb:25:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/application.rb:328:in `require_environment!'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:67:in `console'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:6:in `require'
	from bin/rails:6:in `<main>'
```

Just reporting.

**Comment by differentreality** [comment]
@olea what about `bundle exec rails console`?

**Comment by differentreality** [comment]
Closing due to inactivity
