### ISSUE TITLE
Docker-compose images doesn't work

### ISSUE THREAD

**Issue by linuxonrails** [openSUSE/osem#3126]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**

```
$ bundle
...(everythings ok)
$ docker-compose rm -vf
No stopped containers
$ docker-compose pull
[+] Running 2/2
 ⠿ osem Skipped - No image to be pulled                                                                                                                              0.0s
 ⠿ database Pulled                                                                                                                                                   1.6s
$ docker-compose up 
[+] Running 2/0
 ⠿ Container osem-database-1  Created                                                                                                                                0.0s
 ⠿ Container osem-osem-1      Created                                                                                                                                0.0s
Attaching to osem-database-1, osem-osem-1
osem-database-1  | The files belonging to this database system will be owned by user "postgres".
osem-database-1  | This user must also own the server process.
osem-database-1  | 
osem-database-1  | The database cluster will be initialized with locale "en_US.utf8".
osem-database-1  | The default database encoding has accordingly been set to "UTF8".
osem-database-1  | The default text search configuration will be set to "english".
osem-database-1  | 
osem-database-1  | Data page checksums are disabled.
osem-database-1  | 
osem-database-1  | fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... ok
osem-database-1  | creating subdirectories ... ok
osem-database-1  | selecting dynamic shared memory implementation ... posix
osem-database-1  | selecting default max_connections ... 100
osem-database-1  | selecting default shared_buffers ... 128MB
osem-database-1  | selecting default time zone ... UTC
osem-database-1  | creating configuration files ... ok
osem-database-1  | running bootstrap script ... ok
osem-database-1  | performing post-bootstrap initialization ... sh: locale: not found
osem-database-1  | 2023-02-07 17:44:36.235 UTC [31] WARNING:  no usable system locales were found
osem-osem-1      | 17:44:36 web.1    | started with pid 7
osem-osem-1      | 17:44:36 worker.1 | started with pid 8
osem-database-1  | ok
osem-database-1  | syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
osem-database-1  | You can change this by editing pg_hba.conf or using the option -A, or
osem-database-1  | --auth-local and --auth-host, the next time you run initdb.
osem-database-1  | ok
osem-database-1  | 
osem-database-1  | 
osem-database-1  | Success. You can now start the database server using:
osem-database-1  | 
osem-database-1  |     pg_ctl -D /var/lib/postgresql/data/pgdata -l logfile start
osem-database-1  | 
osem-database-1  | waiting for server to start....2023-02-07 17:44:36.573 UTC [37] LOG:  starting PostgreSQL 12.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
osem-database-1  | 2023-02-07 17:44:36.574 UTC [37] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
osem-database-1  | 2023-02-07 17:44:36.584 UTC [38] LOG:  database system was shut down at 2023-02-07 17:44:36 UTC
osem-database-1  | 2023-02-07 17:44:36.587 UTC [37] LOG:  database system is ready to accept connections
osem-database-1  |  done
osem-database-1  | server started
osem-database-1  | 
osem-database-1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
osem-database-1  | 
osem-database-1  | waiting for server to shut down....2023-02-07 17:44:36.671 UTC [37] LOG:  received fast shutdown request
osem-database-1  | 2023-02-07 17:44:36.672 UTC [37] LOG:  aborting any active transactions
osem-database-1  | 2023-02-07 17:44:36.674 UTC [37] LOG:  background worker "logical replication launcher" (PID 44) exited with exit code 1
osem-database-1  | 2023-02-07 17:44:36.674 UTC [39] LOG:  shutting down
osem-database-1  | 2023-02-07 17:44:36.686 UTC [37] LOG:  database system is shut down
osem-osem-1      | 17:44:36 worker.1 | /usr/lib64/ruby/3.1.0/bundler/definition.rb:507:in `materialize': Could not find nokogiri-1.14.0, rack-2.2.6.2, momentjs-rails-2.29.4.1, zeitwerk-2.6.6, mini_portile2-2.8.1, racc-1.6.2, rails-html-sanitizer-1.5.0, globalid-1.0.1, erubi-1.12.0, minitest-5.17.0, loofah-2.19.1 in locally installed gems (Bundler::GemNotFound)
osem-osem-1      | 17:44:36 worker.1 |  from /usr/lib64/ruby/3.1.0/bundler/definition.rb:187:in `specs'
osem-osem-1      | 17:44:36 worker.1 |  from /usr/lib64/ruby/3.1.0/bundler/definition.rb:244:in `specs_for'
osem-osem-1      | 17:44:36 worker.1 |  from /usr/lib64/ruby/3.1.0/bundler/runtime.rb:18:in `setup'
osem-osem-1      | 17:44:36 worker.1 |  from /usr/lib64/ruby/3.1.0/bundler.rb:161:in `setup'
osem-osem-1      | 17:44:36 worker.1 |  from /usr/lib64/ruby/3.1.0/bundler/setup.rb:20:in `block in <top (required)>'
osem-osem-1      | 17:44:36 worker.1 |  from /usr/lib64/ruby/3.1.0/bundler/ui/shell.rb:136:in `with_level'
osem-osem-1      | 17:44:36 worker.1 |  from /usr/lib64/ruby/3.1.0/bundler/ui/shell.rb:88:in `silence'
osem-osem-1      | 17:44:36 worker.1 |  from /usr/lib64/ruby/3.1.0/bundler/setup.rb:20:in `<top (required)>'
osem-osem-1      | 17:44:36 worker.1 |  from <internal:/usr/lib64/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
osem-osem-1      | 17:44:36 worker.1 |  from <internal:/usr/lib64/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
osem-database-1  |  done
osem-database-1  | server stopped
osem-database-1  | 
osem-database-1  | PostgreSQL init process complete; ready for start up.
osem-database-1  | 
osem-database-1  | 2023-02-07 17:44:36.783 UTC [1] LOG:  starting PostgreSQL 12.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
osem-database-1  | 2023-02-07 17:44:36.783 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
osem-database-1  | 2023-02-07 17:44:36.783 UTC [1] LOG:  listening on IPv6 address "::", port 5432
osem-database-1  | 2023-02-07 17:44:36.785 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
osem-osem-1      | 17:44:36 web.1    | /usr/lib64/ruby/3.1.0/bundler/definition.rb:507:in `materialize': Could not find nokogiri-1.14.0, rack-2.2.6.2, momentjs-rails-2.29.4.1, zeitwerk-2.6.6, mini_portile2-2.8.1, racc-1.6.2, rails-html-sanitizer-1.5.0, globalid-1.0.1, erubi-1.12.0, minitest-5.17.0, loofah-2.19.1 in locally installed gems (Bundler::GemNotFound)
osem-osem-1      | 17:44:36 web.1    |  from /usr/lib64/ruby/3.1.0/bundler/definition.rb:187:in `specs'
osem-osem-1      | 17:44:36 web.1    |  from /usr/lib64/ruby/3.1.0/bundler/definition.rb:244:in `specs_for'
osem-osem-1      | 17:44:36 web.1    |  from /usr/lib64/ruby/3.1.0/bundler/runtime.rb:18:in `setup'
osem-osem-1      | 17:44:36 web.1    |  from /usr/lib64/ruby/3.1.0/bundler.rb:161:in `setup'
osem-osem-1      | 17:44:36 web.1    |  from /usr/lib64/ruby/3.1.0/bundler/setup.rb:20:in `block in <top (required)>'
osem-osem-1      | 17:44:36 web.1    |  from /usr/lib64/ruby/3.1.0/bundler/ui/shell.rb:136:in `with_level'
osem-osem-1      | 17:44:36 web.1    |  from /usr/lib64/ruby/3.1.0/bundler/ui/shell.rb:88:in `silence'
osem-osem-1      | 17:44:36 web.1    |  from /usr/lib64/ruby/3.1.0/bundler/setup.rb:20:in `<top (required)>'
osem-osem-1      | 17:44:36 web.1    |  from <internal:/usr/lib64/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
osem-osem-1      | 17:44:36 web.1    |  from <internal:/usr/lib64/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
osem-database-1  | 2023-02-07 17:44:36.794 UTC [50] LOG:  database system was shut down at 2023-02-07 17:44:36 UTC
osem-database-1  | 2023-02-07 17:44:36.798 UTC [1] LOG:  database system is ready to accept connections
osem-osem-1      | 17:44:37 web.1    | exited with code 1
osem-osem-1      | 17:44:37 system   | sending SIGTERM to all processes
osem-osem-1      | 17:44:37 worker.1 | exited with code 1
osem-osem-1 exited with code 1
```

**Expected correct behavior:**

docker-compose images should work without error.

**Steps to reproduce:**

1. Pull docker images with `docker-compose pull`
2. Run docker images with`docker-compose up`

**Comment by AndrewKvalheim** [comment]
Looks like your `osem` image is outdated. To use #3125 you’ll need to rebuild on the [updated](https://build.opensuse.org/package/revisions/openSUSE:infrastructure:dale/osem-base) base image.

**Comment by linuxonrails** [comment]
> Looks like your `osem` image is outdated. It needs to be rebuilt whenever `Gemfile.lock` changes to include the correct dependencies. Be sure to also pull the [recently updated](https://build.opensuse.org/package/revisions/openSUSE:infrastructure:dale/osem-base) base image to go along with #3125.

It's works!!! Sorry! :sweat_smile:
