### ISSUE TITLE
Error during validation of event type length

### ISSUE THREAD

**Issue by AndrewKvalheim** [openSUSE/osem#3137]
### I'm submitting a…

- [x] Bug Report
- [ ] Feature Request

### Current behavior

When editing an event type, it’s possible to blank the length field:

> <img src="https://user-images.githubusercontent.com/1844746/224217685-d2058a1a-b6ea-45be-bbe8-0d579528722a.png" width="370" src="screenshot" />

This triggers a server error during validation:

```
Started PATCH "/admin/conferences/example/program/event_types/1"
Processing by Admin::EventTypesController#update as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]", "event_type"=>{"title"=>"Talk", "length"=>"", "description"=>"Presentation in lecture format", "minimum_abstract_length"=>"0", "maximum_abstract_length"=>"500", "color"=>"#ff0000"}, "commit"=>"Update Event type", "conference_id"=>"example", "id"=>"1"}
Completed 500 Internal Server Error

NoMethodError (undefined method `%' for nil:NilClass

    errors.add(:length, "must be a divisor of #{program.schedule_interval}") if program && length % program.schedule_interval != 0
                                                                                                  ^):

app/models/event_type.rb:27:in `length_step'
app/controllers/admin/event_types_controller.rb:29:in `update'
```

### Expected correct behavior

Either a validation error (not a server error) is returned or a default value is used.

### Steps to reproduce

1. Create a conference.
2. At *Manage* → *Event Types* → *Edit*, blank the *Length* field and click *Update Event type*.

### Other information

I briefly researched whether the [`length_step`](https://github.com/openSUSE/osem/blob/4de554e0d4dc46adca386fd1dee0aee55a97b091/app/models/event_type.rb#L14) validation could be [made dependent](https://stackoverflow.com/q/5966055) on the [`numericality`](https://github.com/openSUSE/osem/blob/4de554e0d4dc46adca386fd1dee0aee55a97b091/app/models/event_type.rb#L11) validation, but didn’t find a straightforward solution.

**Comment by makrianast** [comment]
i would like to work on that

**Comment by hennevogel** [comment]
@makrianast what's stopping you to submit a pull request?
