### ISSUE TITLE
Investigate flickering test on Travis

### ISSUE THREAD

**Issue by kalabiyau** [openSUSE/osem#354]
```
Failures:
  1) Conference organizer behaves like add and update conference adds a new conference
     Failure/Error: expect(flash).
     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

       TypeError: 'undefined' is not an object (evaluating 'data.datasets[i].data.length')
       TypeError: 'undefined' is not an object (evaluating 'data.datasets[i].data.length')
           at http://127.0.0.1:56720/assets/application.js:46729 in getValueBounds
           at http://127.0.0.1:56720/assets/application.js:46524
           at http://127.0.0.1:56720/assets/application.js:46048
           at http://127.0.0.1:56720/assets/application.js:56847 in draw_line_chart
           at http://127.0.0.1:56720/assets/application.js:56796
           at http://127.0.0.1:56720/assets/application.js:385
           at http://127.0.0.1:56720/assets/application.js:138
           at http://127.0.0.1:56720/assets/application.js:56797
     Shared Example Group: "add and update conference" called from ./spec/features/conference_spec.rb:64
     # ./spec/support/flash.rb:11:in `flash'
     # ./spec/features/conference_spec.rb:32:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:60:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:59:in `block (2 levels) in <top (required)>'
Finished in 2 minutes 15.8 seconds (files took 9.44 seconds to load)
305 examples, 1 failure, 2 pending
```

**Comment by bear454** [comment]
Resolved in #2225
